### ISSUE TITLE
Project One Feedback

### ISSUE THREAD

**Issue by ajhofferber** [benbli/projectOne#1]
Hey Ben,

Nice work on your project.  Cool to see you step out of your comfort zone and tackle Canvas. Seems like you can do some pretty sweet stuff with it. It is also cool that you were able to create your game as a two player version. Plus, I am a sucker for a well-written markdown... :stuck_out_tongue: : 

Did you think about adding some sort of computer mode? Where you could play one player against the computer? How do you think you could go about adding in something like that?

Overall, nice work!

-Ash

**Comment by Avizacherman** [comment]
Ben,

Great work! I know it wasn't exactly what you originally intended with the timing game but I'm impressed with this game of pong. How was working with canvas? I would second Ash's notion of maybe adding some AI. 

Keep pushing onward. 

Score: 3 (check the project Markdown for scoring rubric).

-Avi
